# Generated by Django 4.2.1 on 2023-06-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymnentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('payment_method', models.CharField(max_length=64)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('transactionId', models.IntegerField()),
            ],
        ),
    ]
