# Generated by Django 4.2.3 on 2023-07-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymnentMethod',
            new_name='PaymentMethod',
        ),
    ]
