# Generated by Django 4.2.3 on 2023-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_remove_order_userid_order_cart_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('date_shipped', models.DateTimeField()),
                ('orders', models.ManyToManyField(to='orders.order')),
            ],
        ),
    ]
