# Generated by Django 4.2.3 on 2023-08-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_user'),
        ('cart', '0002_remove_cart_discount_remove_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
