# Generated by Django 4.2.1 on 2023-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('products', models.CharField(max_length=32)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shippingAddress', models.CharField(max_length=100)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderDate_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
