# Generated by Django 4.2.3 on 2023-07-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paymnentmethod_paymentmethod'),
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmethod'),
        ),
    ]
