# Generated by Django 4.2.3 on 2023-07-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_remove_cart_products'),
        ('customer', '0003_alter_customer_user'),
        ('orders', '0003_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userId',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
